package rfc9457

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
)

const ProblemContentType = "application/problem+json"

const fallbackBody = `{"type":"about:blank","status":500,"title":"Internal Server Error","detail":"failed to serialize problem details"}`

// RFC9457 represents a problem details object as defined by RFC 9457
// "Problem Details for HTTP APIs".
//
// https://datatracker.ietf.org/doc/html/rfc9457
type RFC9457 struct {
	// Type is a JSON string containing a URI reference that identifies the
	// problem type. Consumers MUST use the "type" URI (after resolution, if
	// necessary) as the problem type's primary identifier. When this member
	// is not present, its value is assumed to be "about:blank".
	//
	// https://datatracker.ietf.org/doc/html/rfc9457#name-type
	Type string `json:"type"`

	// Status is a JSON number indicating the HTTP status code generated by
	// the origin server for this occurrence of the problem. The "status"
	// member, if present, is only advisory; it conveys the HTTP status code
	// used for the convenience of the consumer.
	//
	// https://datatracker.ietf.org/doc/html/rfc9457#name-status
	Status int `json:"status,omitempty"`

	// Title is a JSON string containing a short, human-readable summary of
	// the problem type. It SHOULD NOT change from occurrence to occurrence
	// of the problem, except for localization. The "title" string is
	// advisory and is included only for users who are unaware of and cannot
	// discover the semantics of the type URI.
	//
	// https://datatracker.ietf.org/doc/html/rfc9457#name-title
	Title string `json:"title,omitempty"`

	// Detail is a JSON string containing a human-readable explanation
	// specific to this occurrence of the problem. The "detail" string, if
	// present, ought to focus on helping the client correct the problem,
	// rather than giving debugging information.
	//
	// https://datatracker.ietf.org/doc/html/rfc9457#name-detail
	Detail string `json:"detail,omitempty"`

	// Instance is a JSON string containing a URI reference that identifies
	// the specific occurrence of the problem.
	//
	// https://datatracker.ietf.org/doc/html/rfc9457#name-instance
	Instance string `json:"instance,omitempty"`

	// Extensions are additional members defined by the problem type. They
	// are flattened into the top-level JSON object on encode and pulled
	// back here on decode. Extension keys must not collide with any
	// reserved member name.
	//
	// https://datatracker.ietf.org/doc/html/rfc9457#name-extension-members
	Extensions map[string]any `json:"-"`
}

// Compile-time interface assertions.
var (
	_ error            = (*RFC9457)(nil)
	_ http.Handler     = (*RFC9457)(nil)
	_ json.Marshaler   = (*RFC9457)(nil)
	_ json.Unmarshaler = (*RFC9457)(nil)
)

var reservedKeys = map[string]struct{}{
	"type":     {},
	"status":   {},
	"title":    {},
	"detail":   {},
	"instance": {},
}

// RFC9457Option configures an [RFC9457] in [NewRFC9457].
type RFC9457Option func(*RFC9457)

// NewRFC9457 builds a problem details object, defaulting Type to
// "about:blank" before applying the supplied options.
func NewRFC9457(options ...RFC9457Option) *RFC9457 {
	r := &RFC9457{
		Type: "about:blank",
	}

	for _, o := range options {
		o(r)
	}

	return r
}

// WithType sets the problem type URI. Use this to point at a documented
// problem-type definition; otherwise leave the default of "about:blank".
func WithType(t string) RFC9457Option {
	return func(r *RFC9457) {
		r.Type = t
	}
}

// WithStatus sets the HTTP status code on the problem.
func WithStatus(i int) RFC9457Option {
	return func(r *RFC9457) {
		r.Status = i
	}
}

// WithTitle sets a short, human-readable summary of the problem type.
func WithTitle(t string) RFC9457Option {
	return func(r *RFC9457) {
		r.Title = t
	}
}

// WithDetail sets a human-readable explanation specific to this occurrence
// of the problem.
func WithDetail(d string) RFC9457Option {
	return func(r *RFC9457) {
		r.Detail = d
	}
}

// WithInstance sets a URI reference identifying the specific occurrence of
// the problem (typically the request path).
func WithInstance(i string) RFC9457Option {
	return func(r *RFC9457) {
		r.Instance = i
	}
}

// Extension is a single extension member: a JSON key and its value.
type Extension struct {
	Key   string
	Value any
}

// NewExtension constructs an [Extension].
func NewExtension(key string, value any) Extension {
	return Extension{
		Key:   key,
		Value: value,
	}
}

// WithExtensions adds extension members to the problem. Calling it multiple
// times merges entries; later keys overwrite earlier ones.
func WithExtensions(e ...Extension) RFC9457Option {
	return func(r *RFC9457) {
		if r.Extensions == nil {
			r.Extensions = make(map[string]any, len(e))
		}
		for _, ext := range e {
			r.Extensions[ext.Key] = ext.Value
		}
	}
}

// FromError builds a problem from a Go error and HTTP status, using
// http.StatusText(status) as the title and err.Error() as the detail.
func FromError(err error, status int) *RFC9457 {
	detail := ""
	if err != nil {
		detail = err.Error()
	}
	return NewRFC9457(
		WithStatus(status),
		WithTitle(http.StatusText(status)),
		WithDetail(detail),
	)
}

// Error implements the error interface so a problem can be returned as a Go
// error. It is safe to call on a nil receiver.
func (r *RFC9457) Error() string {
	if r == nil {
		return "rfc9457: <nil>"
	}
	switch {
	case r.Title != "" && r.Detail != "":
		return fmt.Sprintf("rfc9457: %s: %s", r.Title, r.Detail)
	case r.Title != "":
		return fmt.Sprintf("rfc9457: %s", r.Title)
	case r.Detail != "":
		return fmt.Sprintf("rfc9457: %s", r.Detail)
	default:
		return "rfc9457: problem"
	}
}

// MarshalJSON serializes the problem, flattening Extensions into the top-level
// object. Returns ErrExtensionKeyCollision if an extension key collides with a
// reserved member name.
func (r *RFC9457) MarshalJSON() ([]byte, error) {
	for k := range r.Extensions {
		if _, reserved := reservedKeys[k]; reserved {
			return nil, fmt.Errorf("%w: %q", ErrExtensionKeyCollision, k)
		}
	}

	type alias RFC9457
	base, err := json.Marshal((*alias)(r))
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrUnableToMarshalJSON, err)
	}

	if len(r.Extensions) == 0 {
		return base, nil
	}

	combined := make(map[string]json.RawMessage)
	if err := json.Unmarshal(base, &combined); err != nil {
		return nil, fmt.Errorf("%w: %v", ErrUnableToMarshalJSON, err)
	}
	for k, v := range r.Extensions {
		raw, err := json.Marshal(v)
		if err != nil {
			return nil, fmt.Errorf("%w: %v", ErrUnableToMarshalJSON, err)
		}
		combined[k] = raw
	}
	return json.Marshal(combined)
}

// UnmarshalJSON populates the problem and pulls any non-reserved members into
// Extensions. A missing "type" defaults to "about:blank" per RFC 9457.
func (r *RFC9457) UnmarshalJSON(data []byte) error {
	type alias RFC9457
	tmp := alias{}
	if err := json.Unmarshal(data, &tmp); err != nil {
		return fmt.Errorf("%w: %v", ErrUnableToUnmarshalJSON, err)
	}
	*r = RFC9457(tmp)

	if r.Type == "" {
		r.Type = "about:blank"
	}

	raw := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &raw); err != nil {
		return fmt.Errorf("%w: %v", ErrUnableToUnmarshalJSON, err)
	}
	for k := range reservedKeys {
		delete(raw, k)
	}
	if len(raw) == 0 {
		r.Extensions = nil
		return nil
	}

	extensions := make(map[string]any, len(raw))
	for k, v := range raw {
		var val any
		if err := json.Unmarshal(v, &val); err != nil {
			return fmt.Errorf("%w: %v", ErrUnableToUnmarshalJSON, err)
		}
		extensions[k] = val
	}
	r.Extensions = extensions
	return nil
}

// ToJSON returns the problem encoded as JSON.
func (r *RFC9457) ToJSON() ([]byte, error) {
	return json.Marshal(r)
}

// FromJSON decodes a problem from JSON. Errors are wrapped with
// [ErrUnableToUnmarshalJSON].
func FromJSON(data []byte) (*RFC9457, error) {
	r := &RFC9457{}
	if err := json.Unmarshal(data, r); err != nil {
		if errors.Is(err, ErrUnableToUnmarshalJSON) {
			return nil, err
		}
		return nil, fmt.Errorf("%w: %v", ErrUnableToUnmarshalJSON, err)
	}
	return r, nil
}

// ServeHTTP writes the problem as a application/problem+json response. If
// Status is unset, it defaults to 500 Internal Server Error. If serialization
// fails, a minimal problem body describing the failure is written instead.
func (r *RFC9457) ServeHTTP(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", ProblemContentType)

	body, err := r.ToJSON()
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		_, _ = w.Write([]byte(fallbackBody))
		return
	}

	status := r.Status
	if status == 0 {
		status = http.StatusInternalServerError
	}
	w.WriteHeader(status)
	_, _ = w.Write(body)
}
